name: examples

on:
  pull_request: {}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: setup-python${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get -y install openmpi-bin libopenmpi-dev
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools
        python setup.py sdist

        # Install minimal dependencies and confirm that `import optuna` is successful.
        pip install --progress-bar off $(ls dist/*.tar.gz)
        python -c 'import optuna'

        # Install all dependencies needed for examples.
        pip install --progress-bar off $(ls dist/*.tar.gz)[example] -f https://download.pytorch.org/whl/torch_stable.html
    - name: Run examples
      run: |
        python examples/allennlp/allennlp_simple.py > /dev/null
        python examples/allennlp/allennlp_jsonnet.py > /dev/null
      env:
        OMP_NUM_THREADS: 1
